source("global.R")
## ui.R ##
library(shinydashboard)

dashboardPage(
  skin="purple",
  dashboardHeader(title='Recommendation System'),
  dashboardSidebar(
    sidebarMenu(id='sidebar',
#                 menuItem("Report Overview",tabName='overview',icon=icon("video-camera"),
#                          menuSubItem("Item 1",tabName='item1'),
#                          menuSubItem("Item 2",tabName='item2')),
                menuItem("Recommendation",tabName = 'recommend',icon=icon("video-camera"),
                         menuSubItem("Category",tabName='category'),
                         menuSubItem("New User",tabName='new'),
                         menuSubItem("Old User",tabName='old'))),
    conditionalPanel(condition = "input.sidebar == 'category'",
                     selectInput(inputId = 'cate',label = "Choose Your Category",
                                choices=list("Drama","Adventure","Fantasy","Romance","Action","Family","Comedy","Animation"),
                                selected=1,multiple = F)
                     ,br()
                     # ,actionButton('action1',"Update"),
                     # tags$head(tags$style("#action1{position:absolute;left:11.5px}"))
                     ),
                    
    conditionalPanel(condition = "input.sidebar == 'new'",
                     selectizeInput('newu',"Choose Your Interested Movie",choices=newuser,options = list(maxItems=3),selected="")
                     ,br()),
    conditionalPanel(condition = "input.sidebar == 'old'",
                     selectInput('oldu',"User Id",choices=olduser,selected=1,multiple = F)
                     ,br())),
    dashboardBody(
      tabItems(tabItem("category",
      fixedRow(
        box(tabName='box1',width=6,title="Reconmendation",status='primary',solidHeader = TRUE,
            h4(textOutput(outputId = "cat1"),align = "center"),
            imageOutput(outputId = "catimg1",height=200),
            h4(textOutput(outputId = "cat2"),align = "center"),
            imageOutput(outputId = "catimg2",height=200),
            h4(textOutput(outputId = "cat3"),align = "center"),
            imageOutput(outputId = "catimg3",height=200),
            h4(textOutput(outputId = "cat4"),align = "center"),
            imageOutput(outputId = "catimg4",height=200),
            h4(textOutput(outputId = "cat5"),align = "center"),
            imageOutput(outputId = "catimg5",height=200),
            tags$head(tags$style("#catimg1{position:relative;left:200px}")),
            tags$head(tags$style("#catimg2{position:relative;left:200px}")),
            tags$head(tags$style("#catimg3{position:relative;left:200px}")),
            tags$head(tags$style("#catimg4{position:relative;left:200px}")),
            tags$head(tags$style("#catimg5{position:relative;left:200px}"))
        ),
        box(width=6,title="Top 10 Movies",status='warning',solidHeader = TRUE,
            h4(textOutput(outputId="topname1"),align = "center"),
            imageOutput(outputId = "top1",height=200),
            h4(textOutput(outputId="topname2"),align = "center"),
            imageOutput(outputId = "top2",height=200),
            h4(textOutput(outputId="topname3"),align = "center"),
            imageOutput(outputId = "top3",height=200),
            h4(textOutput(outputId="topname4"),align = "center"),
            imageOutput(outputId = "top4",height=200),
            h4(textOutput(outputId="topname5"),align = "center"),
            imageOutput(outputId = "top5",height=200),
            h4(textOutput(outputId="topname6"),align = "center"),
            imageOutput(outputId = "top6",height=200),
            h4(textOutput(outputId="topname7"),align = "center"),
            imageOutput(outputId = "top7",height=200),
            h4(textOutput(outputId="topname8"),align = "center"),
            imageOutput(outputId = "top8",height=200),
            h4(textOutput(outputId="topname9"),align = "center"),
            imageOutput(outputId = "top9",height=200),
            h4(textOutput(outputId="topname10"),align = "center"),
            imageOutput(outputId = "top10",height=200),
            tags$head(tags$style("#top1{position:relative;left:200px}")),
            tags$head(tags$style("#top2{position:relative;left:200px}")),
            tags$head(tags$style("#top3{position:relative;left:200px}")),
            tags$head(tags$style("#top4{position:relative;left:200px}")),
            tags$head(tags$style("#top5{position:relative;left:200px}")),
            tags$head(tags$style("#top6{position:relative;left:200px}")),
            tags$head(tags$style("#top7{position:relative;left:200px}")),
            tags$head(tags$style("#top8{position:relative;left:200px}")),
            tags$head(tags$style("#top9{position:relative;left:200px}")),
            tags$head(tags$style("#top10{position:relative;left:200px}"))
            
        ))),
      tabItem("new",
              fixedRow(
              box(width=6,title="New User Recommendation",status='danger',solidHeader = TRUE,
                  # textOutput(outputId="test"),
                  h4(textOutput(outputId = "new1"),align = "center"),
                  imageOutput(outputId = "newimg1",height=200),
                  h4(textOutput(outputId = "new2"),align = "center"),
                  imageOutput(outputId = "newimg2",height=200),
                  h4(textOutput(outputId = "new3"),align = "center"),
                  imageOutput(outputId = "newimg3",height=200),
                  h4(textOutput(outputId = "new4"),align = "center"),
                  imageOutput(outputId = "newimg4",height=200),
                  h4(textOutput(outputId = "new5"),align = "center"),
                  imageOutput(outputId = "newimg5",height=200),
                  tags$head(tags$style("#newimg1{position:relative;left:200px}")),
                  tags$head(tags$style("#newimg2{position:relative;left:200px}")),
                  tags$head(tags$style("#newimg3{position:relative;left:200px}")),
                  tags$head(tags$style("#newimg4{position:relative;left:200px}")),
                  tags$head(tags$style("#newimg5{position:relative;left:200px}"))
                  ),
              box(width=6,title="Top 10 Movies",status='warning',solidHeader = TRUE,
                  h4(textOutput(outputId="topname1_n"),align = "center"),
                  imageOutput(outputId = "top1_n",height=200),
                  h4(textOutput(outputId="topname2_n"),align = "center"),
                  imageOutput(outputId = "top2_n",height=200),
                  h4(textOutput(outputId="topname3_n"),align = "center"),
                  imageOutput(outputId = "top3_n",height=200),
                  h4(textOutput(outputId="topname4_n"),align = "center"),
                  imageOutput(outputId = "top4_n",height=200),
                  h4(textOutput(outputId="topname5_n"),align = "center"),
                  imageOutput(outputId = "top5_n",height=200),
                  h4(textOutput(outputId="topname6_n"),align = "center"),
                  imageOutput(outputId = "top6_n",height=200),
                  h4(textOutput(outputId="topname7_n"),align = "center"),
                  imageOutput(outputId = "top7_n",height=200),
                  h4(textOutput(outputId="topname8_n"),align = "center"),
                  imageOutput(outputId = "top8_n",height=200),
                  h4(textOutput(outputId="topname9_n"),align = "center"),
                  imageOutput(outputId = "top9_n",height=200),
                  h4(textOutput(outputId="topname10_n"),align = "center"),
                  imageOutput(outputId = "top10_n",height=200),
                  tags$head(tags$style("#top1_n{position:relative;left:200px}")),
                  tags$head(tags$style("#top2_n{position:relative;left:200px}")),
                  tags$head(tags$style("#top3_n{position:relative;left:200px}")),
                  tags$head(tags$style("#top4_n{position:relative;left:200px}")),
                  tags$head(tags$style("#top5_n{position:relative;left:200px}")),
                  tags$head(tags$style("#top6_n{position:relative;left:200px}")),
                  tags$head(tags$style("#top7_n{position:relative;left:200px}")),
                  tags$head(tags$style("#top8_n{position:relative;left:200px}")),
                  tags$head(tags$style("#top9_n{position:relative;left:200px}")),
                  tags$head(tags$style("#top10_n{position:relative;left:200px}"))
                  ))),
              
      tabItem("old",
              fixedRow(
              box(width=6,title="Old User Recommendation",status='success',solidHeader = T,
                  h4(textOutput(outputId = "old1"),align = "center"),
                  imageOutput(outputId = "oldimg1",height=200),
                  h4(textOutput(outputId = "old2"),align = "center"),
                  imageOutput(outputId = "oldimg2",height=200),
                  h4(textOutput(outputId = "old3"),align = "center"),
                  imageOutput(outputId = "oldimg3",height=200),
                  h4(textOutput(outputId = "old4"),align = "center"),
                  imageOutput(outputId = "oldimg4",height=200),
                  h4(textOutput(outputId = "old5"),align = "center"),
                  imageOutput(outputId = "oldimg5",height=200),
                  tags$head(tags$style("#oldimg1{position:relative;left:200px}")),
                  tags$head(tags$style("#oldimg2{position:relative;left:200px}")),
                  tags$head(tags$style("#oldimg3{position:relative;left:200px}")),
                  tags$head(tags$style("#oldimg4{position:relative;left:200px}")),
                  tags$head(tags$style("#oldimg5{position:relative;left:200px}"))),
              box(width=6,title="Top 10 Movies",status='warning',solidHeader = TRUE,
                  h4(textOutput(outputId="topname1_o"),align = "center"),
                  imageOutput(outputId = "top1_o",height=200),
                  h4(textOutput(outputId="topname2_o"),align = "center"),
                  imageOutput(outputId = "top2_o",height=200),
                  h4(textOutput(outputId="topname3_o"),align = "center"),
                  imageOutput(outputId = "top3_o",height=200),
                  h4(textOutput(outputId="topname4_o"),align = "center"),
                  imageOutput(outputId = "top4_o",height=200),
                  h4(textOutput(outputId="topname5_o"),align = "center"),
                  imageOutput(outputId = "top5_o",height=200),
                  h4(textOutput(outputId="topname6_o"),align = "center"),
                  imageOutput(outputId = "top6_o",height=200),
                  h4(textOutput(outputId="topname7_o"),align = "center"),
                  imageOutput(outputId = "top7_o",height=200),
                  h4(textOutput(outputId="topname8_o"),align = "center"),
                  imageOutput(outputId = "top8_o",height=200),
                  h4(textOutput(outputId="topname9_o"),align = "center"),
                  imageOutput(outputId = "top9_o",height=200),
                  h4(textOutput(outputId="topname10_o"),align = "center"),
                  imageOutput(outputId = "top10_o",height=200),
                  tags$head(tags$style("#top1_o{position:relative;left:200px}")),
                  tags$head(tags$style("#top2_o{position:relative;left:200px}")),
                  tags$head(tags$style("#top3_o{position:relative;left:200px}")),
                  tags$head(tags$style("#top4_o{position:relative;left:200px}")),
                  tags$head(tags$style("#top5_o{position:relative;left:200px}")),
                  tags$head(tags$style("#top6_o{position:relative;left:200px}")),
                  tags$head(tags$style("#top7_o{position:relative;left:200px}")),
                  tags$head(tags$style("#top8_o{position:relative;left:200px}")),
                  tags$head(tags$style("#top9_o{position:relative;left:200px}")),
                  tags$head(tags$style("#top10_o{position:relative;left:200px}"))
                  )#box
      )#tabitem
      )#fixedrow
              
)))


 